config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'about', to: 'pages#about', as: :aaabout
  get 'contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about

  end


  def contact
    @members = [ 'thanh', 'dimitri', 'germain', 'damien', 'julien' ]
    if params[:memberrr]
      @members = @members.select { |member| member.starts_with?(params[:memberrr]) }
    end
  end

  def home
    @colors = ["blue", "red", "orange"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Spoon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <h1>The Spoon</h1> <!-- Add this -->

    <%= yield %>

    <p>A very simple footer</p>  <!-- Add this -->
  </body>
</html>

app/views/pages/about.html.erb
<h1>Our first view 🚀</h1>

app/views/pages/contact.html.erb
<form action="/contact" method="get">
  <input
    type="text"
    name="memberrr"
    value="<%= params[:memberrr] %>"
    placeholder="Who are you looking for?"
  >
  <input type="submit">
</form>

<% @members.each do |member| %>
<ul>
  <li><%= member %></li>
</ul>
<% end %>

app/views/pages/home.html.erb
<h1>Yay</h1>

<% @colors.each do |color| %>
  <h1><%= color %></h1>
<% end %>

<%= link_to "Click me ;)", aaabout_path %>